[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "earthengine-api>=1.7.39",
    "librosa>=1.0.0",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "soundfile>=0.14.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]
